virl:
  subtype: vEdge
  interfaces:
    - network: site2-wan
      name: ge0/0
    - network: site2-guest-lan
      name: ge0/1
    - network: site2-corp-lan
      name: ge0/2
  config_template:  viptela/vedge.j2