vmanage_user: "{{ lookup('env','VMANAGE_USER') | default('admin', true) }}"
vmanage_pass: "{{ lookup('env','VMANAGE_PASS') | default('admin', true) }}"
vmanage_org: "{{ lookup('env','VMANAGE_ORG') | default('', true) }}"
smart_token: "{{ lookup('env','SMART_TOKEN') | default('', true) }}"
ansible_user: "{{ vmanage_user }}"
ansible_password: "{{ vmanage_pass }}"
sdwan_serial_file: "{{ playbook_dir }}/licenses/serialFile.viptela"
sdwan_cert_dir: "{{ lookup('env', 'PWD') }}/myCA"
# Encrypt/Vault this in real life
sdwan_CA_passphrase: Cisc0123
sdwan_CA_cert: "{{ sdwan_cert_dir }}/myCA.pem"
# viptela_version: "{{ lookup('env','VIPTELA_VERSION') | default('18.4.3', true) }}"
viptela_version: "{{ lookup('env','VIPTELA_VERSION') | default('19.2.0', true) }}"
# iosxe_sdwan_version: "{{ lookup('env','IOSXE_SDWAN_VERSION') | default('16.10.2y', true) }}"
iosxe_sdwan_version: "{{ lookup('env','IOSXE_SDWAN_VERSION') | default('16.12.1b', true) }}"

#Terraform VMWare
#vsphere_user: ""
#vsphere_password: ""
#vsphere_server: ""
datacenter: "RTP"
cluster: "cpn-rtp-hx1"
resource_pool: "colab"
datastore: "colab1"
iso_datastore: "colab1"
iso_path: "cloud-init"
vmanage_template: "viptela-vmanage-18.4.302-genericx86-64"
vbond_template: "viptela-edge-18.4.303-genericx86-64"
vsmart_template: "viptela-smart-18.4.303-genericx86-64"
vedge_template: "viptela-edge-18.4.303-genericx86-64"
